[webserver]
SERVER_IP



Add a docker repository
Install docker-ce
Install the docker Python module
Pull the official centos image
Create four containers based on the centos image

---
- hosts: all
  become: true
  vars:
    create_containers: 4
    default_container_name: docker
    default_container_image: centos
    default_container_command: sleep 1d

  tasks:
    - name: Install required system packages
      yum: name={{ item }} state=latest 
      loop: [  'curl', 'python3-pip', 'python3-setuptools']

    - name: Add Docker Repository
      yum_repository:
        name: docker
        file: docker_repos
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        state: present
        gpgcheck: no
        enabled: yes

    - name: Update apt and install docker-ce
      yum: name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
      loop: count={{ create_containers }}

--------------------------------------------------------------------------------------
- name: deploying docker-ce
  hosts: webserver
  tasks:
          - yum:
                  name: wget
                  state: present
          - name: adding repository
            get_url:
                    url: https://download.docker.com/linux/centos/docker-ce.repo
                    dest: /etc/yum.repos.d/

          - name: update containerd.io
            yum:
                name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.13-3.2.el7.x86_64.rpm
                state: latest
            ignore_errors: yes
          - name: install docker-ce
            yum:
                    name: docker-ce
                    state: present
          - name: stating the docker-ce service
            service:
           name: docker
                    state: started
               - name: Install Docker Module for Python
                 pip:
                   name: docker

----------------------------------------------------------

- name: pull image
  hosts: webserver
  tasks:
          - name: pull an image
            docker_image:
                name: centos
                source: pull
~                             
---------------------------------------------------------



- name: create container
  hosts: webserver
  tasks:
          - name: Create a data container
            docker_container:
                name: con2
                image: centos
                command: sleep 1d

---------------------------------------------------------






